version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:10.0.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "yarn.lock" }}
            - v{{ .Environment.CACHE_VERSION }}-dependencies-

      - run: yarn --ignore-engines

      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: ~/app

      - run: yarn lint

      - run: yarn test

      - run: yarn bundlesize

  release:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: ~/app

      - run: yarn build

      - run: yarn release

workflows:
  version: 2
  build-test-release:
    jobs:
      - build

      - test:
          requires:
            - build

      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
